### ISSUE TITLE
Opening the gate results in crash

### ISSUE THREAD

**Issue by fly-man-** [MoreOutput/RockMUD#55]
Missing error handler on `socket`.
TypeError: Cannot read property 'door' of null
    at D:\Development\GitHub\RockMUD\src\commands.js:174:16
    at Room.checkExit (D:\Development\GitHub\RockMUD\src\rooms.js:134:10)
    at D:\Development\GitHub\RockMUD\src\commands.js:173:9
    at D:\Development\GitHub\RockMUD\src\world.js:467:12
    at D:\Development\GitHub\RockMUD\src\world.js:433:11
    at World.checkArea (D:\Development\GitHub\RockMUD\src\world.js:514:11)
    at World.loadArea (D:\Development\GitHub\RockMUD\src\world.js:431:8)
    at World.getRoomObject (D:\Development\GitHub\RockMUD\src\world.js:464:8)
    at Cmd.open (D:\Development\GitHub\RockMUD\src\commands.js:172:9)
    at parseCmd (D:\Development\GitHub\RockMUD\server.js:86:32)

**Comment by MoreOutput** [comment]
blarg; fix in a sec.
