### ISSUE TITLE
Game stops responding after a certain amount of time.

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#91]
(Using the demo app)

**Comment by MoreOutput** [comment]
Running idle on local or do you mean the deployed heroku demo in the readme?

**Comment by wizardsambolton** [comment]
@MoreOutput The heroko demo

**Comment by MoreOutput** [comment]
cool. looking like you may have hit a bug:

2016-08-14T02:52:48.835141+00:00 app[web.1]: Missing error handler on `socket`.
2016-08-14T02:52:48.841465+00:00 app[web.1]: TypeError: msgObj.msg is not a function
2016-08-14T02:52:48.841469+00:00 app[web.1]:     at World.msgPlayer (/app/src/world.js:790:12)
2016-08-14T02:52:48.841470+00:00 app[web.1]:     at Cmd.look (/app/src/commands.js:1435:13)


This will be fixed with the push I do later tonight. I appreciate the notice!

**Comment by wizardsambolton** [comment]
No problem! Just want to say its great to say a js MUD engine thats not dead!

**Comment by MoreOutput** [comment]
Compliments always welcome. This bug should be fixed with the latest push. Some major changes went in -- refinement on those is my main focus right now as I build out the mud school.
