### ISSUE TITLE
Stops responding when you cast 'Spark'

### ISSUE THREAD

**Issue by wizardsambolton** [MoreOutput/RockMUD#97]

**Comment by MoreOutput** [comment]
bleh i must have broke this; will also be fixed this evening.

**Comment by wizardsambolton** [comment]
Awesome thanks!

**Comment by wizardsambolton** [comment]
Oh if you want the error log here it is:

```
Missing error handler on `socket`.
TypeError: fn is not a function
    at Spell.spark (/Users/sambolton/Documents/Github1/RockMUD-master/src/spells.js:42:10)
    at Cmd.cast (/Users/sambolton/Documents/Github1/RockMUD-master/src/commands.js:1293:35)
    at parseCmd (/Users/sambolton/Documents/Github1/RockMUD-master/server.js:62:24)
    at Socket.<anonymous> (/Users/sambolton/Documents/Github1/RockMUD-master/server.js:165:5)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/Users/sambolton/Documents/Github1/RockMUD-master/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/sambolton/Documents/Github1/RockMUD-master/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/sambolton/Documents/Github1/RockMUD-master/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/sambolton/Documents/Github1/RockMUD-master/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
```

**Comment by MoreOutput** [comment]
Fixed and now in master. Moved this to a learned skill on the mage class (learned:true) so it can be easily tested.
